name: priority_queue
author: Paul Brauner <polux@google.com>
homepage: https://github.com/polux/priority_queue
version: 0.1.2
description: A sample command-line application
dev_dependencies:
  args: '>=0.9.0 <0.10.0'
  enumerators: '>=0.5.0 <0.6.0'
  persistent: '>=0.8.0 <0.9.0'
  propcheck: '>=0.4.0 <0.5.0'
  unittest: '>=0.9.0 <0.10.0'
