name: priority_queue
version: 0.1.4
author: Paul Brauner <polux@google.com>
description: A sample command-line application
homepage: https://github.com/polux/priority_queue
dev_dependencies:
  args: '>=0.9.0 <0.13.0'
  enumerators: '>=0.5.5 <0.6.0'
  persistent: '>=0.8.0 <0.9.0'
  propcheck: '>=0.4.0 <0.6.0'
  unittest: '>=0.9.0 <0.12.0'
